name: C/C++ CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  LSL_URL: 'https://github.com/sccn/liblsl/releases/download'
  LSL_RELEASE: '1.13.0'
  LSL_RELEASE_SUFFIX: ''


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: CMake version
      run: cmake --version
    - name: download liblsl (Ubuntu)
      run: |
           curl -L ${LSL_URL}/${LSL_RELEASE}${LSL_RELEASE_SUFFIX}/liblsl-${LSL_RELEASE}-Linux64-bionic.deb -o liblsl.deb
           sudo dpkg -i liblsl.deb
           sudo apt install -y qtbase5-dev
      if: matrix.os == 'ubuntu-latest'
    - name: download liblsl (Windows)
      run: |
           Invoke-WebRequest -Uri $Env:LSL_URL/$Env:LSL_RELEASE$Env:LSL_RELEASE_SUFFIX/liblsl-$Env:LSL_RELEASE-Win64.zip -o liblsl.7z
           7z x liblsl.7z -oLSL
      if: matrix.os == 'windows-latest'
    - name: download liblsl (macOS)
      run: |
           curl -L ${LSL_URL}/${LSL_RELEASE}${LSL_RELEASE_SUFFIX}/liblsl-${LSL_RELEASE}-OSX64.tar.bz2 -o liblsl.tar.bz2
           mkdir LSL
           tar -xvf liblsl.tar.bz2 -C LSL
           brew install qt
           echo '::set-env name=CMAKE_PREFIX_PATH::/usr/local/opt/qt'
      if: matrix.os == 'macOS-latest'
    - name: Install Qt
      # uses: jurplel/install-qt-action@v2
      uses: ouuan/install-qt-action@v2.3.1 # workaround until the aqtinstall timeout is fixed
      with:
        version: 5.14.0
      if: matrix.os == 'windows-latest'
    - name: Configure CMake
      shell: bash
      run: |
           cmake -S . -B build -DLSL_INSTALL_ROOT=$PWD/LSL/ -DCPACK_DEBIAN_PACKAGE_SHLIBDEPS=ON -DCPACK_DEBIAN_PACKAGE_DEPENDS=1
    - name: make
      run: cmake --build build --config Release -j
    - name: package
      run: cmake --build build --config Release -j --target install
    - uses: actions/upload-artifact@master
      with:
        name: pkg-${{ matrix.os }}
        path: build/install
